"""Constants for Agent Mem package."""

# Memory Tier Names
MEMORY_TIER_ACTIVE = "active"
MEMORY_TIER_SHORTTERM = "shortterm"
MEMORY_TIER_LONGTERM = "longterm"

# Entity Types
ENTITY_TYPE_PERSON = "Person"
ENTITY_TYPE_ORGANIZATION = "Organization"
ENTITY_TYPE_CONCEPT = "Concept"
ENTITY_TYPE_TECHNOLOGY = "Technology"
ENTITY_TYPE_LOCATION = "Location"
ENTITY_TYPE_EVENT = "Event"
ENTITY_TYPE_PRODUCT = "Product"

# Relationship Types
REL_TYPE_USES = "USES"
REL_TYPE_IMPLEMENTS = "IMPLEMENTS"
REL_TYPE_DEPENDS_ON = "DEPENDS_ON"
REL_TYPE_RELATES_TO = "RELATES_TO"
REL_TYPE_CONTAINS = "CONTAINS"
REL_TYPE_BELONGS_TO = "BELONGS_TO"

# Database Limits
MAX_SEARCH_RESULTS = 100
DEFAULT_SEARCH_LIMIT = 10
MAX_CHUNK_SIZE = 2000
MIN_CHUNK_SIZE = 100

# Timeouts
DB_CONNECTION_TIMEOUT = 30
EMBEDDING_TIMEOUT = 30
AGENT_TIMEOUT = 120

# Consolidation Thresholds
ACTIVE_TO_SHORTTERM_UPDATE_THRESHOLD = 5
SHORTTERM_TO_LONGTERM_IMPORTANCE_THRESHOLD = 0.7

# Search Weights
DEFAULT_VECTOR_WEIGHT = 0.7
DEFAULT_BM25_WEIGHT = 0.3
DEFAULT_SIMILARITY_THRESHOLD = 0.7
